trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '12.16.1'

- script: npm install
  workingDirectory: src
  displayName: 'Install node dependencies'

- task: Gradle@2
  inputs:
    workingDirectory: 'src/android'
    gradleWrapperFile: 'src/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
